# Generated by Django 5.2.6 on 2025-09-18 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=360, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На модерации'), ('NEEDS_REVISION', 'Нужна доработка'), ('PUBLISHED', 'Опубликовано')], default='DRAFT', max_length=20)),
                ('editor_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='news.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
