# Generated by Django 5.2.6 on 2025-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importednews',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
