# Generated by Django 5.2.6 on 2025-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_archived_at_importednews_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='importednews',
            name='feed_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
