# Generated by Django 5.2.6 on 2025-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_cover_image_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importednews',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Импортированная новость', 'verbose_name_plural': 'Импортированные новости'},
        ),
        migrations.AlterField(
            model_name='article',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='В архиве с'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='news.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor_notes',
            field=models.TextField(blank=True, default='', verbose_name='Заметки редактора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=360, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На модерации'), ('NEEDS_REVISION', 'Нужна доработка'), ('PUBLISHED', 'Опубликовано')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='В архиве с'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='feed_url',
            field=models.URLField(blank=True, default='', verbose_name='Источник RSS'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='image',
            field=models.URLField(blank=True, default='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='link',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
