# Generated by Django 5.2.6 on 2025-09-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
