# Generated by Django 5.2.6 on 2025-09-25 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название источника')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Слаг')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sources/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
            },
        ),
        migrations.RemoveField(
            model_name='importednews',
            name='source',
        ),
        migrations.AddField(
            model_name='importednews',
            name='source_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newssource', verbose_name='Источник'),
        ),
    ]
