# Generated by Django 5.2.6 on 2025-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newssource_remove_importednews_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='article', editable=False, help_text='Тип записи (article)', max_length=20),
        ),
        migrations.AddField(
            model_name='importednews',
            name='type',
            field=models.CharField(default='rss', editable=False, help_text='Тип записи (rss)', max_length=20),
        ),
    ]
