# Generated by Django 5.2.6 on 2025-09-29 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_type_importednews_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='idx_article_pubdesc'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='idx_article_slug'),
        ),
        migrations.AddIndex(
            model_name='importednews',
            index=models.Index(fields=['category', '-published_at'], name='idx_imp_cat_pubdesc'),
        ),
        migrations.AddIndex(
            model_name='importednews',
            index=models.Index(fields=['link'], name='idx_imp_link'),
        ),
    ]
