# Generated by Django 5.2.6 on 2025-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_article_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='idx_article_pubdesc',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='idx_article_slug',
        ),
        migrations.RemoveIndex(
            model_name='importednews',
            name='idx_imp_cat_pubdesc',
        ),
        migrations.RemoveIndex(
            model_name='importednews',
            name='idx_imp_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
