# Generated by Django 5.2.6 on 2025-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_article_idx_article_pubdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importednews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
