# Generated by Django 5.2.6 on 2025-09-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_make_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importednews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
