# Generated by Django 5.2.6 on 2025-09-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_importednews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importednews',
            name='slug',
            field=models.SlugField(blank=True, max_length=360, unique=True, verbose_name='Слаг'),
        ),
    ]
