# Generated by Django 5.2.6 on 2025-10-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_article_views_count_importednews_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsResolverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
