# Generated by Django 5.2.6 on 2025-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_newsresolverlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
