# Generated by Django 5.2.6 on 2025-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_newssource_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(default='article', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='type',
            field=models.CharField(default='rss', editable=False, max_length=20),
        ),
    ]
