# Generated by Django 5.2.6 on 2025-10-05 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_article_type_alter_importednews_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('source_name', models.CharField(max_length=255, verbose_name='Источник')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('level', models.CharField(choices=[('INFO', 'Инфо'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=20)),
            ],
            options={
                'verbose_name': 'Лог импорта RSS',
                'verbose_name_plural': 'Логи импорта RSS',
                'ordering': ['-created_at'],
            },
        ),
    ]
