# Generated by Django 5.2.6 on 2025-10-05 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_rssimportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Панель команд',
                'verbose_name_plural': '🧠 Django Commands',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newsresolverlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог резолвера', 'verbose_name_plural': 'Логи резолвера'},
        ),
        migrations.AlterField(
            model_name='newsresolverlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='newsresolverlog',
            name='level',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='newsresolverlog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newsresolverlog',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='rssimportlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='rssimportlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Инфо'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], db_index=True, default='INFO', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='rssimportlog',
            name='source_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Источник'),
        ),
        migrations.AddIndex(
            model_name='rssimportlog',
            index=models.Index(fields=['source_name', '-created_at'], name='rsslog_src_time_idx'),
        ),
    ]
