# Generated by Django 5.2.6 on 2025-10-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_article_type_alter_importednews_type'),
        ('news', '0021_add_search_indexes'),
    ]

    operations = [
    ]
