# Generated by Django 5.2.6 on 2025-10-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_merge_20251008_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Авторская статья', 'verbose_name_plural': 'Авторские статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='newssource',
            options={'ordering': ['name'], 'verbose_name': 'Источник новостей', 'verbose_name_plural': 'Источники новостей'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг (латиница)'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Слаг (латиница)'),
        ),
    ]
