# Generated by Django 5.2.6 on 2025-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importednews',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Картинка (файл)'),
        ),
        migrations.AddField(
            model_name='importednews',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео (файл)'),
        ),
        migrations.AlterField(
            model_name='importednews',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
