# Generated by Django 5.2.6 on 2025-09-21 19:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
    ]
