# Generated by Django 5.2.6 on 2025-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание (bio)'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, default='', verbose_name='Фото профиля (URL)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Автор'), ('EDITOR', 'Редактор'), ('ADMIN', 'Администратор')], default='AUTHOR', max_length=16, verbose_name='Роль'),
        ),
    ]
