# Generated by Django 5.2.6 on 2025-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_photo_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Автор'), ('EDITOR', 'Редактор'), ('ADMIN', 'Администратор')], default='AUTHOR', max_length=16),
        ),
    ]
