# Generated by Django 5.0.7 on 2025-08-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
