# Generated by Django 5.0.7 on 2025-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_adminlink_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlink',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
