# Generated by Django 5.2.5 on 2025-08-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_is_moderated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(db_column='pub_date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, db_column='image_url', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('author', 'Author')], db_column='source', max_length=200),
        ),
        migrations.AlterModelTable(
            name='news',
            table='news_news',
        ),
    ]
