# Generated by Django 5.2.5 on 2025-08-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_slug_to_category'),
        ('news', '0003_news_is_approved_news_is_popular_alter_news_author_and_more'),
    ]

    operations = [
    ]
