# Generated by Django 5.2.6 on 2025-09-18 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssfeedsource',
            options={'verbose_name': 'Источник RSS', 'verbose_name_plural': 'Источники RSS'},
        ),
        migrations.RemoveField(
            model_name='rssfeedsource',
            name='category',
        ),
        migrations.AddField(
            model_name='rssfeedsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssfeedsource',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='rssfeedsource',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL RSS-ленты'),
        ),
    ]
